### **Importing Required Libraries**

In [23]:
import pandas as pd
import matplotlib as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pickle
import os

### **Loading CSV Data and Creating Data Frame**

In [24]:
data = pd.read_csv(r'C:\Users\njain\OneDrive - Cal State Fullerton\SPRING 2024\CPSC 597 Project\Project\APMBSS\data\processed\weather data\weather_dataset_train.csv')

In [25]:
data.sample(10)

      is_day  cloud_cover  precipitation       mood
4330       0    63.705139       0.289926        Sad
1936       0    42.601319       0.128400      Happy
114        1    24.227815       0.131782  Energetic
2978       0    25.467989       0.361715       Calm
1445       1    44.252354       0.024752      Happy
4275       1    53.369427       1.975691        Sad
3625       0    34.348758       0.231381       Calm
3092       0    55.565030       0.104406       Calm
4853       0    72.949849       1.760022        Sad
1361       1    46.739613       0.052661      Happy

### **Vectorizing Data Using Map Function**

In [26]:
dict_mood = {
    'Energetic': 1,
    'Happy': 2,
    'Calm': 3,
    'Sad': 4
}

data['encoded_mood'] = data['mood'].map(dict_mood)
data.sample(10)

      is_day  cloud_cover  precipitation       mood  encoded_mood
3022       1    68.867855       0.133382       Calm             3
3836       1    22.813440       1.724242        Sad             4
869        1     9.715511       0.056480  Energetic             1
3698       1    18.805982       0.402722       Calm             3
1474       1    17.989790       0.183480      Happy             2
4996       1    57.543346       1.365438        Sad             4
4689       0    50.759029       0.203765        Sad             4
4604       1    47.369932       1.824438        Sad             4
3590       0    34.909866       0.328372       Calm             3
3284       0    40.278176       0.542115       Calm             3

In [15]:
# Dividing data frame into features and target on which the model will fit
features = ['is_day', 'cloud_cover', 'precipitation']
target = ['encoded_mood']

X = data[features]
y = data[target]

In [16]:
X.sample(10)

      is_day  cloud_cover  precipitation
49         0     4.873001       0.087236
330        0    10.707360       0.096794
994        1     2.080714       0.004892
4455       1    61.954090       0.599872
1325       0    44.644056       0.046913
874        0     1.063808       0.115211
1852       0    42.210774       0.132177
4910       1     0.868116       0.983392
3330       0    32.318911       0.303064
4331       0    23.109892       1.933210

In [17]:
y.sample(10)

      encoded_mood
1190             1
2836             3
1806             2
4040             4
440              1
4100             4
2109             2
279              1
2663             3
3006             3

### **Vectorizing Test Data Using Map Function and Dividing into X_train and y_test**

In [20]:
# Loading test dataset using pandas
test_data = pd.read_csv(r'C:\Users\njain\OneDrive - Cal State Fullerton\SPRING 2024\CPSC 597 Project\Project\APMBSS\data\processed\weather data\weather_dataset_test.csv')

# Encoding mood using map() function to vectorize
test_data['encoded_mood'] = test_data['mood'].map(dict_mood)

X_test = test_data.drop('encoded_mood', axis=1)
X_test = X_test.drop('mood', axis=1)

In [21]:
# Viewing test data
X_test.sample(10)

      is_day  cloud_cover  precipitation
1199       0     0.740582       0.446423
334        0     8.356359       0.115064
1610       0    45.177950       1.737796
750        0    45.604693       0.125903
1454       1    30.418949       0.560408
1592       0    53.545525       1.787704
1775       0    39.772510       1.447860
214        1    11.558582       0.083666
841        1    25.724053       0.211444
937        1    42.880840       0.048382

In [22]:
y_test = test_data['encoded_mood']

In [23]:
# Viewing the y_test
y_test

0       1
1       1
2       1
3       1
4       1
       ..
1995    4
1996    4
1997    4
1998    4
1999    4
Name: encoded_mood, Length: 2000, dtype: int64

### **Creating and Training the RandomForestClassifier**

In [24]:
# Creating random forest classifier object
rf = RandomForestClassifier(n_etimators=20, max_depth=10)

In [25]:
# Fitting the training data on random forest classifier
rf.fit(X, y)

c:\Users\njain\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(max_depth=10, n_estimators=20)

### **Predicting the Accuracy**

In [26]:
y_pred = rf.predict(X_test)

In [27]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)

In [28]:
accuracy

0.997

### **Predicting Mood on Random Value**

In [34]:
# 'is_day, cloud_cover, precipitation'
test_random_value = [0, 50, 0.0]

def get_key_from_value(dict_mood, predicted_mood_EncodedValue):
    for key, value in dict_mood.items():
        if value == predicted_mood_EncodedValue:
            return key
    # If the value is not found, you can handle it accordingly
    return None

predicted_mood_EncodedValue = rf.predict([test_random_value])[0]
predicted_mood = get_key_from_value(dict_mood, predicted_mood_EncodedValue)
print(predicted_mood)

Happy

c:\Users\njain\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

### **Saving the Mood Prediction Model from Weather**

In [30]:
# specific path for the model
model_directory = r'C:\Users\njain\OneDrive - Cal State Fullerton\SPRING 2024\CPSC 597 Project\Project\APMBSS\data\models'
model_filename = 'mood_detection_weather_model.pkl'
model_path = os.path.join(model_directory, model_filename)

# Save the model to the specified path
with open(model_path, 'wb') as file:
    pickle.dump(rf, file)

### performance matrix ###

In [33]:
import pandas as pd
import pickle
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [34]:
# Load the model
with open(r'C:\Users\njain\OneDrive - Cal State Fullerton\SPRING 2024\CPSC 597 Project\Project\APMBSS\data\models\mood_detection_weather_model.pkl', 'rb') as f:
    model = pickle.load(f)

In [20]:
from sklearn.ensemble import RandomForestClassifier
model_new = RandomForestClassifier()

In [35]:
# Read the test data from CSV
test_data = pd.read_csv(r'C:\Users\njain\OneDrive - Cal State Fullerton\SPRING 2024\APMBSS_NEW_APPROACH\Cloned Project\W_test_data.csv')

# Assuming the class labels are in the 'mood' column and features start from 'is_day' to 'precipitation'
X_test = test_data.iloc[:, :-1]  # Features
y_true = test_data['mood']      # True labels

In [36]:
# Make predictions
predictions = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_true, predictions)

In [37]:
# Print classification report
print("Accuracy:", accuracy)
print(classification_report(y_true, predictions))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_true, predictions))

Accuracy: 0.9975
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       100
           2       1.00      1.00      1.00       100
           3       0.99      1.00      1.00       100
           4       1.00      0.99      0.99       100

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion Matrix:
[[100   0   0   0]
 [  0 100   0   0]
 [  0   0 100   0]
 [  0   0   1  99]]